package tecnico.depchain.depchain_common;

import java.io.FileWriter;
import java.io.IOException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.Properties;

/**
 * Utility to pre-generate Ed25519 key pairs and write a config.properties file
 * with all the membership information needed by the DepChain system.
 *
 * Usage: java KeyGenUtil <numMembers> <numClients> <outputFilePath>
 *
 * The generated file contains:
 *   - member.count / client.count
 *   - member.<i>.host / port / publickey
 *   - client.<i>.host / port / publickey
 *   - node.<i>.privatekey  (for every member and client)
 *
 * Member IDs:  0 .. numMembers-1
 * Client IDs:  numMembers .. numMembers+numClients-1
 */
public class KeyGenUtil {

	public static void main(String[] args) throws NoSuchAlgorithmException, IOException {
		if (args.length < 3) {
			System.err.println("Usage: java KeyGenUtil <numMembers> <numClients> <outputFilePath>");
			System.exit(1);
		}

		int numMembers = Integer.parseInt(args[0]);
		int numClients = Integer.parseInt(args[1]);
		String outputPath = args[2];

		int memberBasePort = 42069;
		int clientBasePort = 6900;

		KeyPairGenerator kpg = KeyPairGenerator.getInstance("Ed25519");
		Properties props = new Properties();

		props.setProperty("member.count", String.valueOf(numMembers));
		props.setProperty("client.count", String.valueOf(numClients));

		// Generate member (replica) keys
		for (int i = 0; i < numMembers; i++) {
			KeyPair kp = kpg.generateKeyPair();
			String pubB64 = Base64.getEncoder().encodeToString(kp.getPublic().getEncoded());
			String privB64 = Base64.getEncoder().encodeToString(kp.getPrivate().getEncoded());

			props.setProperty("member." + i + ".host", "localhost");
			props.setProperty("member." + i + ".port", String.valueOf(memberBasePort + i));
			props.setProperty("member." + i + ".publickey", pubB64);
			props.setProperty("member." + i + ".depchainAddress",
					String.format("0x%040x", i + 1));
			// node.<id>.privatekey — member IDs are 0-based
			props.setProperty("node." + i + ".privatekey", privB64);
		}

		// Generate client keys
		// Client addresses use repeating hex digits: 0x1111...1111, 0x2222...2222, etc.
		for (int i = 0; i < numClients; i++) {
			KeyPair kp = kpg.generateKeyPair();
			String pubB64 = Base64.getEncoder().encodeToString(kp.getPublic().getEncoded());
			String privB64 = Base64.getEncoder().encodeToString(kp.getPrivate().getEncoded());

			props.setProperty("client." + i + ".host", "localhost");
			props.setProperty("client." + i + ".port", String.valueOf(clientBasePort + i));
			props.setProperty("client." + i + ".publickey", pubB64);
			String hexDigit = Integer.toHexString(i + 1);
			String clientAddr = "0x" + new String(new char[40]).replace('\0', hexDigit.charAt(0));
			props.setProperty("client." + i + ".depchainAddress", clientAddr);
			// Client node IDs start after the members
			int nodeId = numMembers + i;
			props.setProperty("node." + nodeId + ".privatekey", privB64);
		}

		try (FileWriter fw = new FileWriter(outputPath)) {
			props.store(fw, "DepChain PKI Configuration — Auto-generated by KeyGenUtil");
		}

		System.out.println("Config written to " + outputPath);
		System.out.println("  Members: " + numMembers + " (IDs 0.." + (numMembers - 1) + ")");
		System.out.println("  Clients: " + numClients + " (node IDs " + numMembers + ".." + (numMembers + numClients - 1) + ")");
	}
}
